version: '1'

services:
  back:
    environment:
      - WEB_PORT=${WEB_PORT}
    image: back
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml

  db:
    image: postgres:16.1-bullseye
    user: postgres
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mado
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
