volumes:
  meilidata:
    driver: local
  medias:
    driver: local

services:

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - back
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meilidata:/meili_data

  back:
    env_file: .env
    build:
      context: .
    volumes:
      - ${CARDS_FOLDERS}:/data/
      - ${MEDIAS_DIR:-medias}:/medias/
    depends_on:
      - meilisearch
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: .env
