name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'src/**'
          frontend:
            - 'front/**'
    - name: Build the Docker image
      if: steps.filter.output.backend == 'true'
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
